### ISSUE TITLE
Windows GUI not opening

### ISSUE THREAD

**Issue by S-Lucas** [AliView/AliView#109]
Hey all, 

I'm trying to open AliView program to look at some alignments. I get the loading image, but then it fades and the program never actually opens. I'm on Windows 10, and my java version is 1.8.0_311. I tried running AliView v1.27 to no avail. I uninstalled that version and installed v1.28 with the same problem. Any ideas?

S

**Comment by andersla** [comment]
To get some more debugging info, could you please open a Windows Powershell and paste the output of commands below:

`java -version

`And you could download the `aliview.jar` in the directory "without installer version", http://www.ormbunkar.se/aliview/downloads/windows/windows-version-1.28/

java -jar aliview.jar

**Comment by S-Lucas** [comment]
Well, it seems to work now. Thank you.
Here is the output from those commands you asked for.

java -version
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) Client VM (build 25.311-b11, mixed mode)

java -jar aliview.jar
File: C:\Users\Sarah/.AliView/AliView.log
INFO  2021-12-01 12:22:35,267 AliView               84 - version time Wed Nov 24 12:59:48 MST 2021
Time to here in ms = 8
DEBUG 2021-12-01 12:22:35,271 AliView               94 - java.runtime.name=Java(TM) SE Runtime Environment
DEBUG 2021-12-01 12:22:35,271 AliView               94 - sun.boot.library.path=C:\Program Files (x86)\Java\jre1.8.0_311\bin
DEBUG 2021-12-01 12:22:35,271 AliView               94 - java.vm.version=25.311-b11
DEBUG 2021-12-01 12:22:35,272 AliView               94 - java.vm.vendor=Oracle Corporation
DEBUG 2021-12-01 12:22:35,272 AliView               94 - java.vendor.url=http://java.oracle.com/
DEBUG 2021-12-01 12:22:35,272 AliView               94 - path.separator=;
DEBUG 2021-12-01 12:22:35,272 AliView               94 - java.vm.name=Java HotSpot(TM) Client VM
DEBUG 2021-12-01 12:22:35,272 AliView               94 - file.encoding.pkg=sun.io
DEBUG 2021-12-01 12:22:35,272 AliView               94 - user.country=US
DEBUG 2021-12-01 12:22:35,272 AliView               94 - user.script=
DEBUG 2021-12-01 12:22:35,272 AliView               94 - sun.java.launcher=SUN_STANDARD
DEBUG 2021-12-01 12:22:35,272 AliView               94 - sun.os.patch.level=
DEBUG 2021-12-01 12:22:35,272 AliView               94 - java.vm.specification.name=Java Virtual Machine Specification
DEBUG 2021-12-01 12:22:35,272 AliView               94 - user.dir=C:\Users\Sarah\Downloads
DEBUG 2021-12-01 12:22:35,272 AliView               94 - java.runtime.version=1.8.0_311-b11
DEBUG 2021-12-01 12:22:35,272 AliView               94 - java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
DEBUG 2021-12-01 12:22:35,275 AliView               94 - java.endorsed.dirs=C:\Program Files (x86)\Java\jre1.8.0_311\lib\endorsed
DEBUG 2021-12-01 12:22:35,275 AliView               94 - os.arch=x86
DEBUG 2021-12-01 12:22:35,275 AliView               94 - java.io.tmpdir=C:\Users\Sarah\AppData\Local\Temp\
DEBUG 2021-12-01 12:22:35,275 AliView               94 - line.separator=

DEBUG 2021-12-01 12:22:35,275 AliView               94 - java.vm.specification.vendor=Oracle Corporation
DEBUG 2021-12-01 12:22:35,275 AliView               94 - user.variant=
DEBUG 2021-12-01 12:22:35,275 AliView               94 - os.name=Windows 10
DEBUG 2021-12-01 12:22:35,276 AliView               94 - sun.jnu.encoding=Cp1252
DEBUG 2021-12-01 12:22:35,276 AliView               94 - java.library.path=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Users\Sarah\AppData\Local\Microsoft\WindowsApps;;.
DEBUG 2021-12-01 12:22:35,276 AliView               94 - java.specification.name=Java Platform API Specification
DEBUG 2021-12-01 12:22:35,276 AliView               94 - java.class.version=52.0
DEBUG 2021-12-01 12:22:35,276 AliView               94 - sun.management.compiler=HotSpot Client Compiler
DEBUG 2021-12-01 12:22:35,276 AliView               94 - os.version=10.0
DEBUG 2021-12-01 12:22:35,277 AliView               94 - user.home=C:\Users\Sarah
DEBUG 2021-12-01 12:22:35,277 AliView               94 - user.timezone=America/Denver
DEBUG 2021-12-01 12:22:35,277 AliView               94 - java.awt.printerjob=sun.awt.windows.WPrinterJob
DEBUG 2021-12-01 12:22:35,277 AliView               94 - file.encoding=Cp1252
DEBUG 2021-12-01 12:22:35,277 AliView               94 - java.specification.version=1.8
DEBUG 2021-12-01 12:22:35,277 AliView               94 - java.class.path=aliview.jar
DEBUG 2021-12-01 12:22:35,278 AliView               94 - user.name=Sarah
DEBUG 2021-12-01 12:22:35,278 AliView               94 - java.vm.specification.version=1.8
DEBUG 2021-12-01 12:22:35,278 AliView               94 - sun.java.command=aliview.jar
DEBUG 2021-12-01 12:22:35,278 AliView               94 - java.home=C:\Program Files (x86)\Java\jre1.8.0_311
DEBUG 2021-12-01 12:22:35,278 AliView               94 - sun.arch.data.model=32
DEBUG 2021-12-01 12:22:35,278 AliView               94 - user.language=en
DEBUG 2021-12-01 12:22:35,279 AliView               94 - java.specification.vendor=Oracle Corporation
DEBUG 2021-12-01 12:22:35,279 AliView               94 - awt.toolkit=sun.awt.windows.WToolkit
DEBUG 2021-12-01 12:22:35,279 AliView               94 - java.vm.info=mixed mode
DEBUG 2021-12-01 12:22:35,279 AliView               94 - java.version=1.8.0_311
DEBUG 2021-12-01 12:22:35,279 AliView               94 - java.ext.dirs=C:\Program Files (x86)\Java\jre1.8.0_311\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
DEBUG 2021-12-01 12:22:35,279 AliView               94 - sun.boot.class.path=C:\Program Files (x86)\Java\jre1.8.0_311\lib\resources.jar;C:\Program Files (x86)\Java\jre1.8.0_311\lib\rt.jar;C:\Program Files (x86)\Java\jre1.8.0_311\lib\sunrsasign.jar;C:\Program Files (x86)\Java\jre1.8.0_311\lib\jsse.jar;C:\Program Files (x86)\Java\jre1.8.0_311\lib\jce.jar;C:\Program Files (x86)\Java\jre1.8.0_311\lib\charsets.jar;C:\Program Files (x86)\Java\jre1.8.0_311\lib\jfr.jar;C:\Program Files (x86)\Java\jre1.8.0_311\classes
DEBUG 2021-12-01 12:22:35,279 AliView               94 - java.vendor=Oracle Corporation
DEBUG 2021-12-01 12:22:35,279 AliView               94 - sun.stderr.encoding=cp437
DEBUG 2021-12-01 12:22:35,280 AliView               94 - file.separator=\
DEBUG 2021-12-01 12:22:35,280 AliView               94 - java.vendor.url.bug=http://bugreport.sun.com/bugreport/
DEBUG 2021-12-01 12:22:35,280 AliView               94 - sun.io.unicode.encoding=UnicodeLittle
DEBUG 2021-12-01 12:22:35,280 AliView               94 - sun.cpu.endian=little
DEBUG 2021-12-01 12:22:35,280 AliView               94 - sun.desktop=windows
DEBUG 2021-12-01 12:22:35,280 AliView               94 - sun.cpu.isalist=pentium_pro+mmx pentium_pro pentium+mmx pentium i486 i386 i86
INFO  2021-12-01 12:22:35,282 AliView               111 - debugEnvnull
INFO  2021-12-01 12:22:35,284 AliView               135 -  aliview.jar
INFO  2021-12-01 12:22:35,285 AliView               137 - java.vendorOracle Corporation
INFO  2021-12-01 12:22:35,285 AliView               138 - java.version1.8.0_311
INFO  2021-12-01 12:22:35,285 AliView               142 - args.length=0
INFO  2021-12-01 12:22:35,489 AliViewWindow         282 - no file
INFO  2021-12-01 12:22:35,489 AliViewWindow         287 - alignment was null creating new
INFO  2021-12-01 12:22:35,515 CodonRanges           12 - new
INFO  2021-12-01 12:22:35,515 Ranges                44 - add=start=0 end=2147482647 startVal=1
INFO  2021-12-01 12:22:35,515 Ranges                163 - range.toString() count =0 start=0 end=2147482647 startVal=1
DEBUG 2021-12-01 12:22:35,543 AppIcons              138 - iconjavax.swing.ImageIcon@18e2867
INFO  2021-12-01 12:22:35,543 AliViewWindow         421 - inside init()
INFO  2021-12-01 12:22:35,543 AliViewWindow         441 - here
INFO  2021-12-01 12:22:35,557 OSNativeUtils         153 - javaVersion1.8.0_311
INFO  2021-12-01 12:22:35,557 OSNativeUtils         178 - java_version=8.311
INFO  2021-12-01 12:22:35,568 OSNativeUtils         61 - scaleFactorJ6-1.0
DEBUG 2021-12-01 12:22:35,568 OSNativeUtils         105 - Reflection exception? java.lang.NoSuchMethodException: sun.awt.Win32GraphicsDevice.getScaleFactor()
INFO  2021-12-01 12:22:35,568 OSNativeUtils         63 - scaleFactorJ8-1.0
INFO  2021-12-01 12:22:35,584 AlignmentPane         390 - tracking0.4
INFO  2021-12-01 12:22:35,584 AlignmentPane         414 - tracking0.4
INFO  2021-12-01 12:22:35,584 AlignmentPane         276 - charFont10
INFO  2021-12-01 12:22:35,584 AlignmentPane         277 - charPixWidth10
INFO  2021-12-01 12:22:35,666 AlignmentPane         364 - Creating charPixContainers took 82 milliseconds
INFO  2021-12-01 12:22:35,666 AlignmentPane         124 - highDPIScaleFactor1
INFO  2021-12-01 12:22:35,696 AliViewWindow         472 - alignmentPane.isDoubleBuffered()true
INFO  2021-12-01 12:22:35,706 SequenceJList         27 - Create MyDT
INFO  2021-12-01 12:22:35,706 AlignmentListModel    1432 - getLongestSequenceName took 0 milliseconds
INFO  2021-12-01 12:22:35,713 AlignmentPane         1672 - get pref size
INFO  2021-12-01 12:22:35,738 StatusPanel           191 - java.awt.Dimension[width=33491,height=18]
INFO  2021-12-01 12:22:35,739 StatusPanel           201 - java.awt.Dimension[width=33665,height=18]
INFO  2021-12-01 12:22:35,741 AlignmentSelectionModel  352 - hasSelection false 0 milliseconds
INFO  2021-12-01 12:22:35,741 AliViewWindow         614 - middle of GUI
INFO  2021-12-01 12:22:35,741 Alignment             1632 - pos == null
INFO  2021-12-01 12:22:35,742 StatusPanel           277 - Update selection from thread done
DEBUG 2021-12-01 12:22:35,750 AliViewJMenuBar       117 - create menubar
INFO  2021-12-01 12:22:35,756 AliViewJMenuBar       1743 - rebuildRecentFilesSubmenu()
INFO  2021-12-01 12:22:35,824 AliViewWindow         619 - done create menubar
INFO  2021-12-01 12:22:35,839 AlignmentPane         276 - charFont10
INFO  2021-12-01 12:22:35,839 AlignmentPane         277 - charPixWidth10
INFO  2021-12-01 12:22:35,923 AlignmentPane         364 - Creating charPixContainers took 84 milliseconds
INFO  2021-12-01 12:22:35,927 AlignmentPane         276 - charFont10
INFO  2021-12-01 12:22:35,930 AlignmentPane         277 - charPixWidth10
INFO  2021-12-01 12:22:35,956 AlignmentPane         364 - Creating charPixContainers took 29 milliseconds
INFO  2021-12-01 12:22:35,996 AliViewJMenuBar       1762 - rebuildSelectCharsetsSubmenu()utils.nexus.CharSets@93dd95
INFO  2021-12-01 12:22:36,007 AlignmentPane         276 - charFont10
INFO  2021-12-01 12:22:36,007 AlignmentPane         277 - charPixWidth10
INFO  2021-12-01 12:22:36,058 AlignmentPane         364 - Creating charPixContainers took 51 milliseconds
INFO  2021-12-01 12:22:36,071 AlignmentPane         276 - charFont10
INFO  2021-12-01 12:22:36,071 AlignmentPane         277 - charPixWidth10
INFO  2021-12-01 12:22:36,090 AlignmentPane         364 - Creating charPixContainers took 19 milliseconds
INFO  2021-12-01 12:22:36,096 AlignmentPane         276 - charFont10
INFO  2021-12-01 12:22:36,096 AlignmentPane         277 - charPixWidth10
INFO  2021-12-01 12:22:36,173 AlignmentPane         364 - Creating charPixContainers took 77 milliseconds
INFO  2021-12-01 12:22:36,179 AliViewWindow         685 - init() finished
DEBUG 2021-12-01 12:22:36,180 AliView               642 - Inside placeWithinDesktop
INFO  2021-12-01 12:22:36,267 AlignmentPane         1672 - get pref size
INFO  2021-12-01 12:22:36,267 ListTopOffsetJPanel   29 - java.awt.Dimension[width=100,height=25]
INFO  2021-12-01 12:22:36,269 AlignmentPane         1672 - get pref size
INFO  2021-12-01 12:22:36,269 AlignmentPane         1672 - get pref size

**Comment by andersla** [comment]
So it is probably some problem with the installer, could you try also downloading `AliView.exe` from the "Without installer" directory, and try running that one by clicking on it?

**Comment by S-Lucas** [comment]
I uninstalled AliView from my program files, and then ran Aliview.exe. This also worked. The GUI opened.

**Comment by andersla** [comment]
Great!
The only downside running without the file `AliView.l4j.ini` in the same directory as the AliView.exe is that AliView might have problems with very large alignments (because memory is limited by java JVM). You could try creating a file with that name that only contains one line of text (the memory configuration)
` -Xmx1024m`

**Comment by S-Lucas** [comment]
Good to know. I deleted the .jar and the Aliview.exe files, and reran the Aliview-setup.exe file. The GUI works. Thank you for your help Anders!
