### ISSUE TITLE
stop codon count w/ invert mt DNA

### ISSUE THREAD

**Issue by stuckyb** [AliView/AliView#12]
Hello,

Thanks for developing this great software!  Overall, it works very well.

I discovered one relatively minor bug:  When using the invertebrate mitochondrial genetic code, AliView still counts "TGA" as a stop codon, but in the invertebrate mt code, "TGA" codes for tryptophan.

Thanks!

**Comment by AliView** [comment]
Hi, and thanks for your support!
I can not reproduce the problem, I fixed some bugs in the codon count function in Version 1.15, maybe you are running an older version? Check under the Help-menu.
Anders

**Comment by stuckyb** [comment]
Thanks for the response!  I am running version 1.16.  I've tried it on two machines, both running relatively recent versions of XUbuntu, and I get the same thing both places -- AliView is counting TGA as a stop codon even if I tell it to use the invertebrate mt code.

**Comment by AliView** [comment]
Now I found the bug, Thanks for your
      persistence!
      I was trying with the vertebrate mt code when I was looking for
      the bug the first time, but as you write the bug was in the
      invertebrate mt code.
      This will be changed in version 1.18.
      /Anders
      
      On 2015-02-02 01:03, stuckyb wrote:
    
    
      
      Thanks for the response! I am running version 1.16. I've tried
        it on two machines, both running relatively recent versions of
        XUbuntu, and I get the same thing both places -- AliView is
        counting TGA as a stop codon even if I tell it to use the
        invertebrate mt code.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by AliView** [comment]
Fixed in version 1.17.1
/Anders
