### ISSUE TITLE
reading frame bug

### ISSUE THREAD

**Issue by ColinAnthony** [AliView/AliView#14]
in version 1.17.1
When editing an alignment, removing a column, should change the reading frame. two columns after the deletion are not highlighted with amino acid colouring, meaning that the original reading frame from before the deletion is being kept. 
Saving and reopening does not solve the issue.
inserting the relevant number of spaces in all sequences and then deleting the introduced "gap-only column" restores the reading frame.
This was not an issue in previous versions

**Comment by AliView** [comment]
Hi Colin,
I guess this is how I designed AliView - not to delete the reading frame position.
You can easily change the reading frame after deleting a whole column by selecting the part of the alignment that you want to shift and then in Selection menu chose "Set selection as coding starting with position 2, 3, or 1."
Please let me know if this resolves your issue.
Also latest beta version is seemingly stable and editing is now possible when alignment is translated.
All the best,
Anders

**Comment by ColinAnthony** [comment]
Hi Anders,

Thank you. This fixed the issue. I was not aware that you could select different reading frames for different sections of an alignment, but this sound like a great feature to have.
