### ISSUE TITLE
Java: HeadlessException

### ISSUE THREAD

**Issue by pelagial** [AliView/AliView#17]
Hi,

I have installed aliview an several systems in our lab, all on Ubuntu  and it's working finely! However, now on one newly set-up Ubuntu 14.04 computer Aliview doesn't start and returns this error and I have no idea what could cause it. Could you help?

```
INFO  2016-03-18 09:51:27,867 AliView               104 - debugEnvnull
INFO  2016-03-18 09:51:27,907 AliView               124 - -Xmx1024M
INFO  2016-03-18 09:51:27,908 AliView               124 - -Xms512M
INFO  2016-03-18 09:51:27,908 AliView               128 -  /usr/share/aliview/aliview.jar
INFO  2016-03-18 09:51:27,909 AliView               130 - java.vendorOracle Corporation
INFO  2016-03-18 09:51:27,910 AliView               131 - java.version1.7.0_95
INFO  2016-03-18 09:51:27,910 AliView               135 - args.length=0
INFO  2016-03-18 09:51:28,631 AliView               367 - 6
ERROR 2016-03-18 09:51:28,769 AliView               590 -

java.awt.HeadlessException
java.awt.HeadlessException
    at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
    at java.awt.Window.<init>(Window.java:535)
    at java.awt.Frame.<init>(Frame.java:420)
    at java.awt.Frame.<init>(Frame.java:385)
    at javax.swing.JFrame.<init>(JFrame.java:174)
    at aliview.AliViewWindow.<init>(AliViewWindow.java:254)
    at aliview.AliView.createNewAliViewWindow(AliView.java:548)
    at aliview.AliView.main(AliView.java:384)
```

I uploaded the full logfile here: https://www.dropbox.com/s/5z1y3yqec9zk8ef/20160318_aliview.log?dl=0

Thanks,

Fritjof

**Comment by andersla** [comment]
Hi!
      I think it is because the installed java environment on the
      computer is a limited server version and does not include the
      graphical libraries (or a configuration in the java-installation
      that not enables graphical environment).
      Try to investigate what packages java you have installed and
      upgrade to a full java jre installation including graphical
      libraries.
      An alternative is to install Oracle Java 8 as described here:
      
      http://www.ormbunkar.se/aliview/#java8install
      
      All the best,
      Anders
       
      
      On 2016-03-18 10:18, pelagial wrote:
    
    
      Hi,
      I have installed aliview an several systems in our lab, all on
        Ubuntu and it's working finely! However, now on one newly set-up
        Ubuntu 14.04 computer Aliview doesn't start and returns this
        error and I have no idea what could cause it. Could you help?
      `INFO 2016-03-18 09:51:27,867 AliView 104 - debugEnvnull
        INFO 2016-03-18 09:51:27,907 AliView 124 - -Xmx1024M
        INFO 2016-03-18 09:51:27,908 AliView 124 - -Xms512M
        INFO 2016-03-18 09:51:27,908 AliView 128 -
        /usr/share/aliview/aliview.jar
        INFO 2016-03-18 09:51:27,909 AliView 130 - java.vendorOracle
        Corporation
        INFO 2016-03-18 09:51:27,910 AliView 131 - java.version1.7.0_95
        INFO 2016-03-18 09:51:27,910 AliView 135 - args.length=0
        INFO 2016-03-18 09:51:28,631 AliView 367 - 6
        ERROR 2016-03-18 09:51:28,769 AliView 590 -
      java.awt.HeadlessException
        java.awt.HeadlessException
        at
        java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
        at java.awt.Window.(Window.java:535)
        at java.awt.Frame.(Frame.java:420)
        at java.awt.Frame.(Frame.java:385)
        at javax.swing.JFrame.(JFrame.java:174)
        at aliview.AliViewWindow.(AliViewWindow.java:254)
        at aliview.AliView.createNewAliViewWindow(AliView.java:548)
        at aliview.AliView.main(AliView.java:384)`
      I uploaded the full logfile here: https://www.dropbox.com/s/5z1y3yqec9zk8ef/20160318_aliview.log?dl=0
      Thanks,
      Fritjof
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly or view it on
          GitHub

**Comment by pelagial** [comment]
Oh, stupid me :) Many thanks for the hint, works perfectly now.
