### ISSUE TITLE
website blocked

### ISSUE THREAD

**Issue by ColinAnthony** [AliView/AliView#18]
FYI someone had the web page rated as containing malware...
I cannot access http://www.ormbunkar.se/aliview/ but am redirected to a warning page
I have requested a re-rating via:
http://www.brightcloud.com/tools/url-ip-lookup.php

**Comment by andersla** [comment]
Thanks! Probably because it is on a university server and some university servers where hijacked for a ddos attack recently. 

Colin Anthony <notifications@github.com> skrev: (1 april 2016 17:05:09 CEST)
>FYI someone had the web page rated as containing malware...
>I cannot access http://www.ormbunkar.se/aliview/ but am redirected to a
>warning page
>I have requested a re-rating via:
>http://www.brightcloud.com/tools/url-ip-lookup.php
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/AliView/AliView/issues/18

Hälsar Anders
