### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by hlibyar** [AliView/AliView#20]
I have problems to open AliView on my PC. 
Error message as follow:

"The registry refers to a nonexistent Java Runtime Environment installation or the runtime is corrupted"
The system cannot find the path specified.

**Comment by AliView** [comment]
Hi,
      I am sorry but I don't think it is a speciffic AliView error, but
      Java installation problem:
      http://superuser.com/questions/269343/java-issue-nonexistent-java-runtime
      You should not need to adjust the PATH variable?
      Reinstall / uninstall JAVA?
      I myself are mostly running Linux so I can not really help you
      with this issue:(
      Please let me know if you get/not it working.
      /Anders
      
      
      On 2016-08-01 21:54, Hongmei wrote:
    
    
      I have problems to open AliView on my PC. 
        Error message as follow:
      "The registry refers to a nonexistent Java Runtime Environment
        installation or the runtime is corrupted"
        The system cannot find the path specified.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on
          GitHub, or mute
          the thread.
