### ISSUE TITLE
Consenus Toggle

### ISSUE THREAD

**Issue by BecFaustie** [AliView/AliView#24]
I have problem with the display. I am no longer able to toggle between the consensus and non-consensus displays. It is permanently set to 'highlight consensus characters' and toggling on any of the other 'highlight' options does not change the display. I would appreciate it if some could point out what I'm doing wrong - it's got me baffled.

**Comment by andersla** [comment]
Hi! I haven't come across this issue before! could you share the alignment or part of it? Have you tried to delete and reinstall AliView? Also delete directory .AliView in your Home directory. What Operating system are you using?

**Comment by BecFaustie** [comment]
I have already tried deleting and reinstalling AliView. My operating system is Windows 10. I have deleted the .AliView folder before attempting a reinstall. I've also tried resinstalling an earlier version (1.17.1)

Aliview had crashed prior to this problem and I received a notification it was due to a memory issue. At the time, I was cutting and pasting different alignments into a master compilation that had become quite large. All alignments l load into Aliview are affected but are not corrupted because I can view them normally with Aliview on another computer.

I'm not sure if the memory crash was just a coincicdent but it appears my computer can no longer properly display Aliview. When I highlight a sequence, the individual characters are greyed out as opposed to being individually coloured, I can't toggle the consensus character option off and the background has reverted  to white. It looks like its related to some display parameter issue with my computer that may or may not have been triggered by the memory crash. Any ideas?

**Comment by andersla** [comment]
I forgot that on Windows the user
      settings are stored in the registry and not in the .AliView
      directory.
      Please start Regedit (just type Regedit in "Search Windows" then
      navidate to and delete the settings:
      HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\aliview
      Let's hope this is will solve this issue.
      If you want to assign more memory to AliView (I recommend that),
      then see: http://www.ormbunkar.se/aliview/#memory_settings
      /Anders
      
      
      
      On 2017-03-02 23:59, BecFaustie wrote:
    
    I have already tried deleting and reinstalling
      AliView. My operating system is Windows 10. I have deleted the
      .AliView folder before attempting a reinstall. I've also tried
      resinstalling an earlier version (1.17.1)
      
      Aliview had crashed prior to this problem and I received a
      notification it was due to a memory issue. At the time, I was
      cutting and pasting different alignments into a master compilation
      that had become quite large. All alignments l load into Aliview
      are affected but are not corrupted because I can view them
      normally with Aliview on another computer.
      
      I'm not sure if the memory crash was just a coincicdent but it
      appears my computer can no longer properly display Aliview. When I
      highlight a sequence, the individual characters are greyed out as
      opposed to being individually coloured, I can't toggle the
      consensus character option off and the background has reverted to
      white. It looks like its related to some display parameter issue
      with my computer that may or may not have been triggered by the
      memory crash. Any ideas?

**Comment by BecFaustie** [comment]
Thanks – awesome advice and all working normally now.

**Comment by andersla** [comment]
Happy we could solve it:)
