### ISSUE TITLE
find "internal" gaps

### ISSUE THREAD

**Issue by eberlejonas** [AliView/AliView#27]
Hi, thanks for this lightweight, easy-to-use alignment editor! It's becoming my favorite for quick (and more thourough) checks of my alignments.

Is there a way to use the search-function to find only internal gaps, i.e., not `-` at the beginning or the end of the sequences but in the middle?
This would greatly facilitate finding sequencing errors in large, gap-less coding regions.
I understand that I can search e.g. A or T using [AT]; however, regular expressions like `\w-+\w` (which would find internal gaps) seem not to be supported.
Jonas

**Comment by andersla** [comment]
Hi Jonas,
Thanks for your kind words about AliView!
Yes you can search for `n-n` (the IUPAC n will match any char (but gap) then a gap and then  n again). The search function also allow any number of gaps in between searched for letters (it is looking for a sequence - not gaps).
The regular expressions are not really working - I will look into it.
/Anders

**Comment by eberlejonas** [comment]
Hi Anders,
great! Thanks for the fast reply!
All the best,
Jonas
