### ISSUE TITLE
failure to launch after increasing memory usage setting

### ISSUE THREAD

**Issue by ColinAnthony** [AliView/AliView#34]
editing the AliView.l4j.ini in windows, 

from 1024M to 2048M, 

causes aliview to crash on launch

(windows 10, aliview v1.18)

**Comment by andersla** [comment]
You probably have 32bit Java on your system - then java heap is limited. If you need more memory you should install 64 bit java. (If your java is installed in "Program files (x86)" then it is 32bit)

**Comment by ColinAnthony** [comment]
Thanks!
That solved it.
