### ISSUE TITLE
Aliview no longer opens on MacBook Air

### ISSUE THREAD

**Issue by Machaon01** [AliView/AliView#45]
I've been using Aliview for about a year  and just today it stopped opening. No error message.  It looks like it's going to open (the little icon appears on my screen and Aliview appears in the  menu bar) I  downloaded the latest version, same problem. No other issues with any other software.

Anyone else ever have this problem?  Any ideas?

**Comment by andersla** [comment]
Unfortunately I don't run AliView on OSX myself....I will see what I can find on a friends computer.

**Comment by andersla** [comment]
Could you please run this command from your terminal and paste error-message or output here please?
`java -jar /Applications/AliView.app/Contents/Resources/Java/repo/AliView/AliView/1.20/AliView-1.20.jar`

**Comment by Machaon01** [comment]
Error: Unable to access jarfile /Applications/AliView.app/Contents/Resources/Java/repo/AliView/AliView/1.20/AliView-1.20.jar

Thanks Anders, my OIT guys sorted it out (sort of, since I just realized whatever they did stopped Eclipse from working) but Aliview is now working fine

D

**Comment by andersla** [comment]
Great!
