### ISSUE TITLE
Window size/position on open

### ISSUE THREAD

**Issue by Shellfishgene** [AliView/AliView#53]
How is the size and position of the main windows handled? It seems Aliview remembers the last size and postion, but not always. Sometimes it opens in a very small window in the upper left of the screen. Also, when it was maximized when closing, the next time it opens in a windows that fills the screen, but is not properly maximized (on Windows).

**Comment by andersla** [comment]
Thanks for reporting the issues!

If the latest saved position is outside current desktop size or if didn't get saved properly - then it opens a small window in upper left corner to be sure it is visible.
I fixed the issue with not properly restoring a maximized window - it should work in version 1.22 (will be published within the next few days). It might also be dependant on OS and Java-version whether it works or not.

Sorry for the late reply - I had missed the notifications from github:-)

**Comment by andersla** [comment]
Maximized window should be fixed in v1.22.
Please reopen if that is not the case.
