### ISSUE TITLE
serious bug in "align selected sequence" in Aliview 1.21

### ISSUE THREAD

**Issue by willfischer** [AliView/AliView#54]
Effect: extra copy of newly aligned sequence put at bottom of alignment; most menu items (including save!) thereafter greyed-out and inaccessible.

Actions preceding: "align selected sequence" using mafft version v7.369b (2017/Dec/2) with two different parameter sets -- but alignment with muscle behaves correctly. "Close this type of output window when done" IS checked, but it doesn't close for mafft (it does close for muscle). 

Interpretation: failure to exit alignment process and close window when using mafft leaves the menus in a "funny" state.

Notes: Same effect with either Align ADD program set to "/usr/local/bin/mafft"  and Command parameters "--add SECOND_SEQUENCES --out TEMP_OUT_FILE CURRENT_ALIGNMENT_FASTA" or with Command parameters "--addfull SECOND_SEQUENCES --out TEMP_OUT_FILE CURRENT_ALIGNMENT_FASTA"

Alignment dimensions: 19 sequences, 12907 columns

alignment progress window output (1 of 2):

command:
 /usr/local/bin/mafft --add /var/folders/2l/dy9t3yfd5w9618dmlt4d499w0000gq/T/aliview-tmp-selected-alignment_6106703522497406606fasta --out /var/folders/2l/dy9t3yfd5w9618dmlt4d499w0000gq/T/aliview-tmp-alignment_691420346262081660.fasta /var/folders/2l/dy9t3yfd5w9618dmlt4d499w0000gq/T/aliview-tmp-unselected-alignment_197202485558940712fasta

nadd = 1
nthread = 0
nthreadpair = 0
nthreadtb = 0
stacksize: 8192 kb
generating a scoring matrix for nucleotide (dist=200) ... done
Gap Penalty = -1.53, +0.00, +0.00

Making a distance matrix ..

    1 / 19
done.

Constructing a UPGMA tree (efffree=0) ... 

    0 / 19
   10 / 19
done.

Progressive alignment 1/2... 

STEP    18 / 18  f
done.

Making a distance matrix from msa.. 

    0 / 19
done.

Constructing a UPGMA tree (efffree=1) ... 

    0 / 19
   10 / 19
done.

Progressive alignment 2/2... 

STEP    18 / 18  f
done.

disttbfast (nuc) Version 7.369
alg=A, model=DNA200 (2), 1.53 (4.59), -0.00 (-0.00), noshift, amax=0.0
0 thread(s)

Strategy:
 FFT-NS-2 (Fast but rough)
 Progressive method (guide trees were built 2 times.)

If unsure which option to use, try 'mafft --auto input > output'.
For more information, see 'mafft --help', 'mafft --man' and the mafft page.

The default gap scoring scheme has been changed in version 7.110 (2013 Oct).
It tends to insert more gaps into gap-rich regions than previous versions.
To disable this change, add the --leavegappyregion option.

alignment output window (2 of 2)

command:
 /usr/local/bin/mafft --addfull /var/folders/2l/dy9t3yfd5w9618dmlt4d499w0000gq/T/aliview-tmp-selected-alignment_4789178130833953576fasta --out /var/folders/2l/dy9t3yfd5w9618dmlt4d499w0000gq/T/aliview-tmp-alignment_7047152793169207668.fasta /var/folders/2l/dy9t3yfd5w9618dmlt4d499w0000gq/T/aliview-tmp-unselected-alignment_4965105259874097496fasta

nadd = 3
generating a scoring matrix for nucleotide (dist=200) ... done
   1/  16
   2/  16
   3/  16
   4/  16
   5/  16
   6/  16
   7/  16
   8/  16
   9/  16
  10/  16
  11/  16
  12/  16
  13/  16
  14/  16
  15/  16
dndpre (nuc) Version 7.369
alg=X, model=DNA200 (2), 2.00 (6.00), -0.10 (-0.30), noshift, amax=0.0
0 thread(s)

generating a scoring matrix for nucleotide (dist=200) ... done
All-to-all alignment.
    0 / 16
    1 / 16
    2 / 16
    3 / 16
    4 / 16
    5 / 16
    6 / 16
    7 / 16
    8 / 16
    9 / 16
   10 / 16
   11 / 16
   12 / 16
   13 / 16
   14 / 16
   15 / 16

##### writing hat3
pairlocalalign (nuc) Version 7.369
alg=Y, model=DNA200 (2), 2.00 (6.00), -0.10 (-0.30), noshift, amax=0.0
0 thread(s)

nadd = 3
nthread = 0
blosum 62 / kimura 200
sueff_global = 0.100000
norg = 16
njobc = 17
Loading 'hat3' ... 
done.
generating a scoring matrix for nucleotide (dist=200) ... done
Loading 'hat2n' (aligned sequences - new sequences) ... done.
Loading 'hat2i' (aligned sequences) ... done.

0 / 3                    
c
1 / 3                    
c
2 / 3                    
c

Combining ..
0 / 3
 0 / 3

   done.                      

   done.                      

addsingle (nuc) Version 7.369
alg=A, model=DNA200 (2), 1.53 (4.59), -0.00 (-0.00), noshift, amax=0.0
0 thread(s)

Strategy:
 Multi-INS-full (Not tested.)
 ?

If unsure which option to use, try 'mafft --auto input > output'.
For more information, see 'mafft --help', 'mafft --man' and the mafft page.

The default gap scoring scheme has been changed in version 7.110 (2013 Oct).
It tends to insert more gaps into gap-rich regions than previous versions.
To disable this change, add the --leavegappyregion option.

**Comment by andersla** [comment]
Hi and sorry for the late reply - I had missed the notifications from github:-)
I can not reproduce the error.
I am using mafft version 7.394 on Linux.
Maybe there is something with that set of sequences?
But I would be very happy if we could find out why AliView locks on the error - It sould still give control to user and report error.
If you can reproduce error and before that activate logging (Menu File -> Show message log.
At the end of that log window  there will be an indication of where log file is saved. Usually /Users/xxx/.AliView/
When program errors after alignment. Please get and upload log file or send it by email.

**Comment by Shellfishgene** [comment]
I also get that sometimes, usually when the alignment program crashes, for example when it is out of RAM. I don't have a reproducible case, I will add one here if it happens again. I guess there are cases when the alignment program stops, but AliView doesn't notice and waits forever?

**Comment by andersla** [comment]
Yes that's what I think happens - but in 1.22 (released within the next few days) I will change the code a bit trying to catch more errors and giving better option to break out of waiting.

**Comment by andersla** [comment]
Hopefully fixed with 1.22
