### ISSUE TITLE
Redundant "overwrite file" dialog on Windows

### ISSUE THREAD

**Issue by Shellfishgene** [AliView/AliView#55]
If you save a file as an already existing one, the Windows file picker generates a "Do you want to overwrite" dialog, and upon clicking "yes" Aliview creates another one. Only slightly annoying ;).

**Comment by andersla** [comment]
I can not reproduce this, I am running Windows 10 1703 and Java(TM) SE Runtime Environment (build 9.0.1+11)

**Comment by Shellfishgene** [comment]
I just tried it again (with ver 1.22), Windows 7, Java 8, still happens as described, excuse the German...

![image](https://user-images.githubusercontent.com/1769465/38542736-f61a5d14-3ca2-11e8-81f2-7c5d68900bf6.png)
Upon clicking "yes":
![image](https://user-images.githubusercontent.com/1769465/38542742-fa6f6a08-3ca2-11e8-8e31-d2a402500344.png)

**Comment by andersla** [comment]
Thank you for images, I will look into it further.

**Comment by andersla** [comment]
Fixed in Version 1.23 (I think) if you are using Java 8 or higher. Problem was not limiting an old workaround to only Java 7, but to all Java versions 7 or higher.
