### ISSUE TITLE
Opening files by double clicking in aliview

### ISSUE THREAD

**Issue by amartinezgarcia** [AliView/AliView#58]
I have set aliview as my default program to work on alignments. However, when I double click on a fasta file, aliview starts without problems, but the file does not open directly - I need to go to File > Open File > and select the file again.
I tried to download a new version of the program, but it did not help...

Do you know how to improve this?

Thanks a lot.

**Comment by andersla** [comment]
Hi @amartinezgarcia Could you please let me know what OS you are using? Windows? OSX? Linux? Version? And also could you please paste the debug log here? "File"->"Show message log".

**Comment by amartinezgarcia** [comment]
Dear Anders,

Thanks a lot for your answer and sorry for the my clumsiness formulating
the questions with so important details missing... My computer runs on a
macOS High Sierra 10.13.3. The logmessage is quite long... I attach it to
this message.
Alejandro

2018-04-11 11:47 GMT+02:00 Anders Larsson <notifications@github.com>:
