### ISSUE TITLE
Residue numbering

### ISSUE THREAD

**Issue by vcristal** [AliView/AliView#60]
I'm using AliView to visualize an alignment done by the Kalign tool. The problem is Kalign doesn't include in the alignment the residue numbering of each sequence. Can AliView automatically number the residues of each sequence? or Do I have to do it manually? Thanks for your time.

**Comment by andersla** [comment]
I am sorry I don't really understand, I have never used Kalign, I always use mafft. Could you give an example of numbered residues and also maybe what is the reason why the numbering is needed?

**Comment by vcristal** [comment]
Thanks, it is ok. I figured it out.
