### ISSUE TITLE
The resolution is too low on MacOS

### ISSUE THREAD

**Issue by billzt** [AliView/AliView#68]
Although I've seen the    `<key>NSHighResolutionCapable</key>` string in the config files, the resolution of sequences is still too low on MacOS to view it clearly.

<img width="172" alt="屏幕快照 2019-04-07 18 33 45" src="https://user-images.githubusercontent.com/1146090/55682265-b97b2300-5963-11e9-8e88-04efff207101.png">

**Comment by andersla** [comment]
Thanks for your report!
I was just working on a bug fix!
Would you mind testing this pre-release version 1.26 to see if issue is fixed?
http://www.ormbunkar.se/aliview/downloads/mac/beta/AliView-1.26-app.zip

**Comment by billzt** [comment]
Yeah, it has been fixed. Thank you
