### ISSUE TITLE
Windows 10 error: Can't save files

### ISSUE THREAD

**Issue by DJKitchin** [AliView/AliView#71]
Thanks for a great app. When trying to save alignments (in any format) I get an error. This seems to be linked to the latest batch of Windows 10 updates, as Aliview was working fine before. Don't know if anyone else has had this problem?

**Comment by andersla** [comment]
Sorry for late reply, No I don't have the problem on my Windows 10 computer.
Could you please post error message.
Maybe something with java-version and latest AliView. 
Could you plese try with previous working version?
Could you post aliview debug log?

**Comment by DJKitchin** [comment]
Quick update: This no longer seems to be an issue, updated Java and reinstalled AliView on the pc that was giving issues and everything is working again.
