### ISSUE TITLE
Windows with OpenJDK

### ISSUE THREAD

**Issue by Shellfishgene** [AliView/AliView#88]
Hi!

We can't use the Oracle Java version anymore, and I installed OpenJDK14 from "Adopt OpenJDK". When starting the Aliview from the `.exe` installed by the Windows installer it just complains it needs Java 15 and opens the Oracle page. Using the `.jar` version works. Is there a setting that's missing? I checked the optionts to set the `JAVA_HOME` environment variable and registrty values in the Adopt OpenJDK installer.

**Comment by andersla** [comment]
Next AliView release is updated to latest Launch4J. JAVA_HOME might not be enough, you might need to tick RegistryKeys option in OpenJava Installer. https://github.com/AliView/AliView/commit/6bd006e0af5c500f659df87a632d4a422a076839

**Comment by Shellfishgene** [comment]
Works for me now, thanks!

**Comment by sadiogo** [comment]
I'm having the same problem. I tried installing OpenJDK 19 from zip and manually setting up JAVA_HOME and then installing OpenJDK 17 via the Microsoft Build OpenJDK msi installer. In both cases I get the Java 15 error.
