### ISSUE TITLE
AliView ERROR launching on Mac OS BigSur

### ISSUE THREAD

**Issue by camilogarciabotero** [AliView/AliView#97]
Hi all,

Thanks for working on this amazing tool, I've using AliView a lot and found it essential in my work!

I've just updated my Mac into BigSur and tried to run AliView again and got the following window error message:

<img width="532" alt="Screen Shot 2021-03-06 at 4 49 43 PM" src="https://user-images.githubusercontent.com/25586362/110221836-676b1100-7e9c-11eb-9f1b-83f86ff00317.png">

The thing is that I'm using the following Java version on my machine:

```
java --version
```

```
openjdk 11.0.8 2020-07-14 LTS
OpenJDK Runtime Environment Zulu11.41+23-CA (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.41+23-CA (build 11.0.8+10-LTS, mixed mode)
```

I tried to reinstall AliView again, but the same window emerged again.

Thanks a lot and if more information in this regard is needed I'll be glad to share it.
Cheers,
Camilo.

**Comment by andersla** [comment]
Thanks for your bug-report! I am not running OSX myself, but I updated the start-script on the OSX version of AliView. Could you please test the 1.27-beta1in beta download folder: https://ormbunkar.se/aliview/downloads/mac/beta/

**Comment by camilogarciabotero** [comment]
Hi @andersla 

That was a very quick response. I just tried this version release and it is working pretty smoothly. 

Thanks for solving this bug that fast!
Camilo
